### ISSUE TITLE
Old tiletype dissapears

### ISSUE THREAD

**Issue by ohrling** [spirotris/sipi18-group1project2#13] opened 2019-03-21 09:03 UTC
At this stage, when the character moves onto the door without having a treasure the door dissapears and won't come back when character exits.
This bug should appear when the monsters start to move.

Possible fix: add a check when moving character/monster onto a Point, if the original Point is a treasure or a door then store it in a Field to be able to revert on movement out of that Point.

**Comment by ohrling** [comment] 2019-03-22 11:58
The logics are fixed, only FX fixes remaining.

**Comment by ohrling** [comment] 2019-03-22 13:59
Your turn @spirotris 🙂

**Comment by spirotris** [comment] 2019-03-22 14:12
Caused by moveCharacter()! The onCollision() method needs to check whether you're walking into a treasure and remember it so it can set the 'old' tile to something like 'OPENTREASURE' again once you move. Same for the door/ladder..

https://github.com/spirotris/sipi18-group1project2/blob/master/src/game/Gameboard.java#L50
https://github.com/spirotris/sipi18-group1project2/blob/master/src/game/Gameboard.java#L58

I can fix this tomorrow if you're done for the day.

**Comment by Marcizz** [comment] 2019-03-23 19:06
This is now fixed in the latest PR. Close this when #17 is merged.

**Closed as completed** 2019-03-23 19:34 UTC
Labels: bug
